services:
  stadium-app-local:
    build:
      context: .
      dockerfile: Dockerfile
    image: pe-stadiumbookingbe:latest
    ports:
      - "443:8443" # HTTPS port
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - KEYSTORE_PATH=${KEYSTORE_PATH}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - MAILGUN_FROM_EMAIL=${MAILGUN_FROM_EMAIL}
    volumes:
      - ./keystore.p12:/app/keystore.p12
    env_file:
      - .env
    restart: unless-stopped

x-pre-build:
  stadium-app-local:
    pre_build:
      - docker stop stadium-app || true
      - docker rm stadium-app || true
      - docker rmi pe-stadiumbookingbe:latest || true
