name: Deploy Spring Boot App to DigitalOcean

on:
  push:
    branches:
      - main  # or your default branch


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pe-stadiumbookingbe .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/pe-stadiumbookingbe

      - name: Deploy to DigitalOcean via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_SSH_HOST }}
          username: ${{ secrets.DO_SSH_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pe-stadiumbookingbe
            docker stop stadium-app || true
            docker rm stadium-app || true
            docker run -d --name stadium-app -p 80:8080 ${{ secrets.DOCKERHUB_USERNAME }}/pe-stadiumbookingbe
