name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pe-stadiumbookingbe .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pe-stadiumbookingbe

      - name: Deploy on Droplet via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_SSH_HOST }}
          username: ${{ secrets.DO_SSH_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pe-stadiumbookingbe
            docker stop stadium-app || true
            docker rm stadium-app || true
            docker run -d --name stadium-app -p 80:8080 ${{ secrets.DOCKERHUB_USERNAME }}/pe-stadiumbookingbe
